/**
 * Country base data according to international standards
 */
INSERT INTO Country (country_id, name, iso_alpha_2, iso_alpha_3, ioc_code) VALUES
(004,  'Afghanistan',                                           'AF',                              'AFG',  'AFG'),
(008,  'Albania',                                               'AL',                              'ALB',  'ALB'),
(010,  'Antarctica',                                            'AQ',                              'ATA',  ''   ),
(012,  'Algeria',                                               'DZ',                              'DZA',  'ALG'),
(016,  'American Samoa',                                        'AS',                              'ASM',  'ASA'),
(020,  'Andorra',                                               'AD',                              'AND',  'AND'),
(024,  'Angola',                                                'AO',                              'AGO',  'ANG'),
(028,  'Antigua and Barbuda',                                   'AG',                              'ATG',  'ANT'),
(031,  'Azerbaijan',                                            'AZ',                              'AZE',  'AZE'),
(032,  'Argentina',                                             'AR',                              'ARG',  'ARG'),
(036,  'Australia',                                             'AU',                              'AUS',  'AUS'),
(040,  'Austria',                                               'AT',                              'AUT',  'AUT'),
(044,  'Bahamas',                                               'BS',                              'BHS',  'BAH'),
(048,  'Bahrain',                                               'BH',                              'BHR',  'BRN'),
(050,  'Bangladesh',                                            'BD',                              'BGD',  'BAN'),
(051,  'Armenia',                                               'AM',                              'ARM',  'ARM'),
(052,  'Barbados',                                              'BB',                              'BRB',  'BAR'),
(056,  'Belgium',                                               'BE',                              'BEL',  'BEL'),
(060,  'Bermuda',                                               'BM',                              'BMU',  'BER'),
(064,  'Bhutan',                                                'BT',                              'BTN',  'BHU'),
(068,  'Bolivia (Plurinational State of)',                      'BO',                              'BOL',  'BOL'),
(070,  'Bosnia and Herzegovina',                                'BA',                              'BIH',  'BIH'),
(072,  'Botswana',                                              'BW',                              'BWA',  'BOT'),
(074,  'Bouvet Island',                                         'BV',                              'BVT',  ''   ),
(076,  'Brazil',                                                'BR',                              'BRA',  'BRA'),
(084,  'Belize',                                                'BZ',                              'BLZ',  'BIZ'),
(086,  'British Indian Ocean Territory',                        'IO',                              'IOT',  ''   ),
(090,  'Solomon Islands',                                       'SB',                              'SLB',  'SOL'),
(092,  'Virgin Islands (British)',                              'VG',                              'VGB',  'IVB'),
(096,  'Brunei Darussalam',                                     'BN',                              'BRN',  'BRU'),
(100,  'Bulgaria',                                              'BG',                              'BGR',  'BUL'),
(104,  'Myanmar',                                               'MM',                              'MMR',  'MYA'),
(108,  'Burundi',                                               'BI',                              'BDI',  'BDI'),
(112,  'Belarus',                                               'BY',                              'BLR',  'BLR'),
(116,  'Cambodia',                                              'KH',                              'KHM',  'CAM'),
(120,  'Cameroon',                                              'CM',                              'CMR',  'CMR'),
(124,  'Canada',                                                'CA',                              'CAN',  'CAN'),
(132,  'Cabo Verde',                                            'CV',                              'CPV',  'CPV'),
(136,  'Cayman Islands',                                        'KY',                              'CYM',  'CAY'),
(140,  'Central African Republic',                              'CF',                              'CAF',  'CAF'),
(144,  'Sri Lanka',                                             'LK',                              'LKA',  'SRI'),
(148,  'Chad',                                                  'TD',                              'TCD',  'CHA'),
(152,  'Chile',                                                 'CL',                              'CHL',  'CHI'),
(156,  'China',                                                 'CN',                              'CHN',  'CHN'),
(158,  'Taiwan',                                                'TW',                              'TWN',  'TPE'),
(162,  'Christmas Island',                                      'CX',                              'CXR',  ''   ),
(166,  'Cocos (Keeling) Islands',                               'CC',                              'CCK',  ''   ),
(170,  'Colombia',                                              'CO',                              'COL',  'COL'),
(174,  'Comoros',                                               'KM',                              'COM',  'COM'),
(175,  'Mayotte',                                               'YT',                              'MYT',  ''   ),
(178,  'Congo',                                                 'CG',                              'COG',  'CGO'),
(180,  'Congo (Democratic Republic of the)',                    'CD',                              'COD',  'COD'),
(184,  'Cook Islands',                                          'CK',                              'COK',  'COK'),
(188,  'Costa Rica',                                            'CR',                              'CRI',  'CRC'),
(191,  'Croatia',                                               'HR',                              'HRV',  'CRO'),
(192,  'Cuba',                                                  'CU',                              'CUB',  'CUB'),
(196,  'Cyprus',                                                'CY',                              'CYP',  'CYP'),
(203,  'Czechia',                                               'CZ',                              'CZE',  'CZE'),
(204,  'Benin',                                                 'BJ',                              'BEN',  'BEN'),
(208,  'Denmark',                                               'DK',                              'DNK',  'DEN'),
(212,  'Dominica',                                              'DM',                              'DMA',  'DMA'),
(214,  'Dominican Republic',                                    'DO',                              'DOM',  'DOM'),
(218,  'Ecuador',                                               'EC',                              'ECU',  'ECU'),
(222,  'El Salvador',                                           'SV',                              'SLV',  'ESA'),
(226,  'Equatorial Guinea',                                     'GQ',                              'GNQ',  'GEQ'),
(231,  'Ethiopia',                                              'ET',                              'ETH',  'ETH'),
(232,  'Eritrea',                                               'ER',                              'ERI',  'ERI'),
(233,  'Estonia',                                               'EE',                              'EST',  'EST'),
(234,  'Faroe Islands',                                         'FO',                              'FRO',  'FRO'),
(238,  'Falkland Islands (Malvinas)',                           'FK',                              'FLK',  ''   ),
(239,  'South Georgia and the South Sandwich Islands',          'GS',                              'SGS',  ''   ),
(242,  'Fiji',                                                  'FJ',                              'FJI',  'FIJ'),
(246,  'Finland',                                               'FI',                              'FIN',  'FIN'),
(248,  'Åland Islands',                                         'AX',                              'ALA',  ''   ),
(250,  'France',                                                'FR',                              'FRA',  'FRA'),
(254,  'French Guiana',                                         'GF',                              'GUF',  ''   ),
(258,  'French Polynesia',                                      'PF',                              'PYF',  ''   ),
(260,  'French Southern Territories',                           'TF',                              'ATF',  ''   ),
(262,  'Djibouti',                                              'DJ',                              'DJI',  'DJI'),
(266,  'Gabon',                                                 'GA',                              'GAB',  'GAB'),
(268,  'Georgia',                                               'GE',                              'GEO',  'GEO'),
(270,  'Gambia',                                                'GM',                              'GMB',  'GAM'),
(275,  'Palestine, State of',                                   'PS',                              'PSE',  'PLE'),
(276,  'Germany',                                               'DE',                              'DEU',  'GER'),
(288,  'Ghana',                                                 'GH',                              'GHA',  'GHA'),
(292,  'Gibraltar',                                             'GI',                              'GIB',  ''   ),
(296,  'Kiribati',                                              'KI',                              'KIR',  'KIR'),
(300,  'Greece',                                                'GR',                              'GRC',  'GRE'),
(304,  'Greenland',                                             'GL',                              'GRL',  ''   ),
(308,  'Grenada',                                               'GD',                              'GRD',  'GRN'),
(312,  'Guadeloupe',                                            'GP',                              'GLP',  ''   ),
(316,  'Guam',                                                  'GU',                              'GUM',  'GUM'),
(320,  'Guatemala',                                             'GT',                              'GTM',  'GUA'),
(324,  'Guinea',                                                'GN',                              'GIN',  'GUI'),
(328,  'Guyana',                                                'GY',                              'GUY',  'GUY'),
(332,  'Haiti',                                                 'HT',                              'HTI',  'HAI'),
(334,  'Heard Island and McDonald Islands',                     'HM',                              'HMD',  ''   ),
(336,  'Holy See',                                              'VA',                              'VAT',  ''   ),
(340,  'Honduras',                                              'HN',                              'HND',  'HON'),
(344,  'Hong Kong',                                             'HK',                              'HKG',  'HKG'),
(348,  'Hungary',                                               'HU',                              'HUN',  'HUN'),
(352,  'Iceland',                                               'IS',                              'ISL',  'ISL'),
(356,  'India',                                                 'IN',                              'IND',  'IND'),
(360,  'Indonesia',                                             'ID',                              'IDN',  'INA'),
(364,  'Iran (Islamic Republic of)',                            'IR',                              'IRN',  'IRI'),
(368,  'Iraq',                                                  'IQ',                              'IRQ',  'IRQ'),
(372,  'Ireland',                                               'IE',                              'IRL',  'IRL'),
(376,  'Israel',                                                'IL',                              'ISR',  'ISR'),
(380,  'Italy',                                                 'IT',                              'ITA',  'ITA'),
(384,  'Côte d’Ivoire',                                         'CI',                              'CIV',  'CIV'),
(388,  'Jamaica',                                               'JM',                              'JAM',  'JAM'),
(392,  'Japan',                                                 'JP',                              'JPN',  'JPN'),
(398,  'Kazakhstan',                                            'KZ',                              'KAZ',  'KAZ'),
(400,  'Jordan',                                                'JO',                              'JOR',  'JOR'),
(404,  'Kenya',                                                 'KE',                              'KEN',  'KEN'),
(408,  'Korea (Democratic People’s Republic of)',               'KP',                              'PRK',  'PRK'),
(410,  'Korea (Republic of)',                                   'KR',                              'KOR',  'KOR'),
(414,  'Kuwait',                                                'KW',                              'KWT',  'KUW'),
(417,  'Kyrgyzstan',                                            'KG',                              'KGZ',  'KGZ'),
(418,  'Lao People’s Democratic Republic',                      'LA',                              'LAO',  'LAO'),
(422,  'Lebanon',                                               'LB',                              'LBN',  'LIB'),
(426,  'Lesotho',                                               'LS',                              'LSO',  'LES'),
(428,  'Latvia',                                                'LV',                              'LVA',  'LAT'),
(430,  'Liberia',                                               'LR',                              'LBR',  'LBR'),
(434,  'Libya',                                                 'LY',                              'LBY',  'LBA'),
(438,  'Liechtenstein',                                         'LI',                              'LIE',  'LIE'),
(440,  'Lithuania',                                             'LT',                              'LTU',  'LTU'),
(442,  'Luxembourg',                                            'LU',                              'LUX',  'LUX'),
(446,  'Macao',                                                 'MO',                              'MAC',  ''   ),
(450,  'Madagascar',                                            'MG',                              'MDG',  'MAD'),
(454,  'Malawi',                                                'MW',                              'MWI',  'MAW'),
(458,  'Malaysia',                                              'MY',                              'MYS',  'MAS'),
(462,  'Maldives',                                              'MV',                              'MDV',  'MDV'),
(466,  'Mali',                                                  'ML',                              'MLI',  'MLI'),
(470,  'Malta',                                                 'MT',                              'MLT',  'MLT'),
(474,  'Martinique',                                            'MQ',                              'MTQ',  ''   ),
(478,  'Mauritania',                                            'MR',                              'MRT',  'MTN'),
(480,  'Mauritius',                                             'MU',                              'MUS',  'MRI'),
(484,  'Mexico',                                                'MX',                              'MEX',  'MEX'),
(492,  'Monaco',                                                'MC',                              'MCO',  'MON'),
(496,  'Mongolia',                                              'MN',                              'MNG',  'MGL'),
(498,  'Moldova (Republic of)',                                 'MD',                              'MDA',  'MDA'),
(499,  'Montenegro',                                            'ME',                              'MNE',  'MNE'),
(500,  'Montserrat',                                            'MS',                              'MSR',  ''   ),
(504,  'Morocco',                                               'MA',                              'MAR',  'MAR'),
(508,  'Mozambique',                                            'MZ',                              'MOZ',  'MOZ'),
(512,  'Oman',                                                  'OM',                              'OMN',  'OMA'),
(516,  'Namibia',                                               'NA',                              'NAM',  'NAM'),
(520,  'Nauru',                                                 'NR',                              'NRU',  'NRU'),
(524,  'Nepal',                                                 'NP',                              'NPL',  'NEP'),
(528,  'Netherlands',                                           'NL',                              'NLD',  'NED'),
(531,  'Curaçao',                                               'CW',                              'CUW',  ''   ),
(533,  'Aruba',                                                 'AW',                              'ABW',  'ARU'),
(534,  'Sint Maarten (Dutch part)',                             'SX',                              'SXM',  ''   ),
(535,  'Bonaire, Sint Eustatius and Saba',                      'BQ',                              'BES',  ''   ),
(540,  'New Caledonia',                                         'NC',                              'NCL',  ''   ),
(548,  'Vanuatu',                                               'VU',                              'VUT',  'VAN'),
(554,  'New Zealand',                                           'NZ',                              'NZL',  'NZL'),
(558,  'Nicaragua',                                             'NI',                              'NIC',  'NCA'),
(562,  'Niger',                                                 'NE',                              'NER',  'NIG'),
(566,  'Nigeria',                                               'NG',                              'NGA',  'NGR'),
(570,  'Niue',                                                  'NU',                              'NIU',  ''   ),
(574,  'Norfolk Island',                                        'NF',                              'NFK',  ''   ),
(578,  'Norway',                                                'NO',                              'NOR',  'NOR'),
(580,  'Northern Mariana Islands',                              'MP',                              'MNP',  ''   ),
(581,  'United States Minor Outlying Islands',                  'UM',                              'UMI',  ''   ),
(583,  'Micronesia (Federated States of)',                      'FM',                              'FSM',  'FSM'),
(584,  'Marshall Islands',                                      'MH',                              'MHL',  'MHL'),
(585,  'Palau',                                                 'PW',                              'PLW',  'PLW'),
(586,  'Pakistan',                                              'PK',                              'PAK',  'PAK'),
(591,  'Panama',                                                'PA',                              'PAN',  'PAN'),
(598,  'Papua New Guinea',                                      'PG',                              'PNG',  'PNG'),
(600,  'Paraguay',                                              'PY',                              'PRY',  'PAR'),
(604,  'Peru',                                                  'PE',                              'PER',  'PER'),
(608,  'Philippines',                                           'PH',                              'PHL',  'PHI'),
(612,  'Pitcairn',                                              'PN',                              'PCN',  ''   ),
(616,  'Poland',                                                'PL',                              'POL',  'POL'),
(620,  'Portugal',                                              'PT',                              'PRT',  'POR'),
(624,  'Guinea-Bissau',                                         'GW',                              'GNB',  'GBS'),
(626,  'Timor-Leste',                                           'TL',                              'TLS',  'TLS'),
(630,  'Puerto Rico',                                           'PR',                              'PRI',  'PUR'),
(634,  'Qatar',                                                 'QA',                              'QAT',  'QAT'),
(638,  'Réunion',                                               'RE',                              'REU',  ''   ),
(642,  'Romania',                                               'RO',                              'ROU',  'ROU'),
(643,  'Russian Federation',                                    'RU',                              'RUS',  'RUS'),
(646,  'Rwanda',                                                'RW',                              'RWA',  'RWA'),
(652,  'Saint Barthélemy',                                      'BL',                              'BLM',  ''   ),
(654,  'Saint Helena, Ascension and Tristan da Cunha',          'SH',                              'SHN',  ''   ),
(659,  'Saint Kitts and Nevis',                                 'KN',                              'KNA',  'SKN'),
(660,  'Anguilla',                                              'AI',                              'AIA',  ''   ),
(662,  'Saint Lucia',                                           'LC',                              'LCA',  'LCA'),
(663,  'Saint Martin (French part)',                            'MF',                              'MAF',  ''   ),
(666,  'Saint Pierre and Miquelon',                             'PM',                              'SPM',  ''   ),
(670,  'Saint Vincent and the Grenadines',                      'VC',                              'VCT',  'VIN'),
(674,  'San Marino',                                            'SM',                              'SMR',  'SMR'),
(678,  'Sao Tome and Principe',                                 'ST',                              'STP',  'STP'),
(682,  'Saudi Arabia',                                          'SA',                              'SAU',  'KSA'),
(686,  'Senegal',                                               'SN',                              'SEN',  'SEN'),
(688,  'Serbia',                                                'RS',                              'SRB',  'SRB'),
(690,  'Seychelles',                                            'SC',                              'SYC',  'SEY'),
(694,  'Sierra Leone',                                          'SL',                              'SLE',  'SLE'),
(702,  'Singapore',                                             'SG',                              'SGP',  'SIN'),
(703,  'Slovakia',                                              'SK',                              'SVK',  'SVK'),
(704,  'Viet Nam',                                              'VN',                              'VNM',  'VIE'),
(705,  'Slovenia',                                              'SI',                              'SVN',  'SLO'),
(706,  'Somalia',                                               'SO',                              'SOM',  'SOM'),
(710,  'South Africa',                                          'ZA',                              'ZAF',  'RSA'),
(716,  'Zimbabwe',                                              'ZW',                              'ZWE',  'ZIM'),
(724,  'Spain',                                                 'ES',                              'ESP',  'ESP'),
(728,  'South Sudan',                                           'SS',                              'SSD',  'SSD'),
(729,  'Sudan',                                                 'SD',                              'SDN',  'SUD'),
(732,  'Western Sahara',                                        'EH',                              'ESH',  ''   ),
(740,  'Suriname',                                              'SR',                              'SUR',  'SUR'),
(744,  'Svalbard and Jan Mayen',                                'SJ',                              'SJM',  ''   ),
(748,  'Swaziland',                                             'SZ',                              'SWZ',  'SWZ'),
(752,  'Sweden',                                                'SE',                              'SWE',  'SWE'),
(756,  'Switzerland',                                           'CH',                              'CHE',  'SUI'),
(760,  'Syrian Arab Republic',                                  'SY',                              'SYR',  'SYR'),
(762,  'Tajikistan',                                            'TJ',                              'TJK',  'TJK'),
(764,  'Thailand',                                              'TH',                              'THA',  'THA'),
(768,  'Togo',                                                  'TG',                              'TGO',  'TOG'),
(772,  'Tokelau',                                               'TK',                              'TKL',  ''   ),
(776,  'Tonga',                                                 'TO',                              'TON',  'TGA'),
(780,  'Trinidad and Tobago',                                   'TT',                              'TTO',  'TRI'),
(784,  'United Arab Emirates',                                  'AE',                              'ARE',  'UAE'),
(788,  'Tunisia',                                               'TN',                              'TUN',  'TUN'),
(792,  'Turkey',                                                'TR',                              'TUR',  'TUR'),
(795,  'Turkmenistan',                                          'TM',                              'TKM',  'TKM'),
(796,  'Turks and Caicos Islands',                              'TC',                              'TCA',  ''   ),
(798,  'Tuvalu',                                                'TV',                              'TUV',  'TUV'),
(800,  'Uganda',                                                'UG',                              'UGA',  'UGA'),
(804,  'Ukraine',                                               'UA',                              'UKR',  'UKR'),
(807,  'Macedonia (the former Yugoslav Republic of)',           'MK',                              'MKD',  'MKD'),
(818,  'Egypt',                                                 'EG',                              'EGY',  'EGY'),
(826,  'United Kingdom of Great Britain and Northern Ireland',  'GB',                              'GBR',  'GBR'),
(831,  'Guernsey',                                              'GG',                              'GGY',  ''   ),
(832,  'Jersey',                                                'JE',                              'JEY',  ''   ),
(833,  'Isle of Man',                                           'IM',                              'IMN',  ''   ),
(834,  'Tanzania, United Republic of',                          'TZ',                              'TZA',  'TAN'),
(840,  'United States of America',                              'US',                              'USA',  'USA'),
(850,  'Virgin Islands (U.S.)',                                 'VI',                              'VIR',  'ISV'),
(854,  'Burkina Faso',                                          'BF',                              'BFA',  'BUR'),
(858,  'Uruguay',                                               'UY',                              'URY',  'URU'),
(860,  'Uzbekistan',                                            'UZ',                              'UZB',  'UZB'),
(862,  'Venezuela (Bolivarian Republic of)',                    'VE',                              'VEN',  'VEN'),
(876,  'Wallis and Futuna',                                     'WF',                              'WLF',  ''   ),
(882,  'Samoa',                                                 'WS',                              'WSM',  'SAM'),
(887,  'Yemen',                                                 'YE',                              'YEM',  'YEM'),
(894,  'Zambia',                                                'ZM',                              'ZMB',  'ZAM')
