name: "Chromatic"

on:
  push:
    branches: [master]

defaults:
  run:
    shell: bash
    working-directory: app

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@v10
        with:
          workingDir: app
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
